FROM node

WORKDIR /home/Projects

RUN echo "version 1"

RUN git clone https://github.com/kweonminsung/docker_study.git

WORKDIR /home/Projects/docker_study/frontend

RUN npm install

CMD ["npm", "start"]