FROM python:3.10

WORKDIR /home/Projects

RUN echo "version 1"

RUN git clone https://github.com/kweonminsung/docker_study.git

WORKDIR /home/Projects/docker_study/backend

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

CMD ["uvicorn", "main:app", "--reload", "--port", "3001"]